[package]

name = "rustrest"
version = "0.0.1"
authors = ["Glyn Normington <glyn.normington@gmail.com>"]

[dependencies]
hyper = "0.10.7"
hyper-native-tls = "0.2.2"
futures = "0.1.13"
tokio-core = "0.1.6"
pretty_env_logger = "0.1.0"
